version: "3.7"
services:
  nest:
    build:
      args:
        - NODE_VER=22.12.0
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    volumes:
      - type: bind
        source: .
        target: /home/node/app
      - type: volume
        source: node_modules
        target: /home/node/app/nest-app/node_modules
    depends_on:
      - postgresql
    networks:
      - pride-project

  postgresql:
    env_file: ".env"
    container_name: postgresql
    image: postgres:16.6
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    hostname: postgres
    restart: always
    networks:
      - pride-project

volumes:
  node_modules:
  postgres_data:

networks:
  pride-project:
    external: true
