version: "3.7"
services:
  nest:
    build:
      args:
        - NODE_VER=22.12.0
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    volumes:
      - type: bind
        source: .
        target: /home/node/app
      - type: volume
        source: node_modules
        target: /home/node/app/nest-app/node_modules
  postgresql:
    env_file: ".env"
    container_name: postgresql
    user: root
    image: postgres:16.6
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./postgres/data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./postgres/init
        target: /docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always

  pgadmin4:
    env_file: ".env"
    user: "${UID}:${GID}"
    image: dpage/pgadmin4:8.14
    container_name: pgadmin4
    ports:
      - 81:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    hostname: pgadmin4
    links:
      - postgresql
    restart: always

volumes:
  node_modules:
